#
# Scene Manager - Scenes Configuration
#
# This file is auto-generated by the Scene Manager plugin
# You can edit it manually, but it's recommended to use the Scene Manager UI panel
#
extends Node

var scenes: Dictionary = {
	"_auto_refresh": true,
	"_auto_save": false,
	"_ignore_list": ["res://addons"],
	"_ignores_visible": true,
	"_sections": ["Menu", "Game"],

	# Menu scenes
	"main_menu": {
		"sections": ["Menu"],
		"settings": {"All": {"subsection": "", "visibility": true}, "Menu": {"subsection": "", "visibility": true}},
		"value": "res://examples/space_shooter/scenes/main_menu.tscn"
	},
	"pilot_selection": {
		"sections": ["Menu"],
		"settings": {"All": {"subsection": "", "visibility": true}, "Menu": {"subsection": "", "visibility": true}},
		"value": "res://examples/space_shooter/scenes/pilot_selection.tscn"
	},
	"ship_selection": {
		"sections": ["Menu"],
		"settings": {"All": {"subsection": "", "visibility": true}, "Menu": {"subsection": "", "visibility": true}},
		"value": "res://examples/space_shooter/scenes/ship_selection.tscn"
	},

	# Game scenes
	"main_game": {
		"sections": ["Game"],
		"settings": {"All": {"subsection": "", "visibility": true}, "Game": {"subsection": "", "visibility": true}},
		"value": "res://examples/space_shooter/scenes/main_game.tscn"
	}
}
